### ISSUE TITLE
Hinzufügen eines neuen Models?

### ISSUE THREAD

**Issue by joerglox** [BenediktSeidl/prpd_usb#2]
Hallo,
wäre es möglich einen PR50SBi 9562281 hinzuzufügen?
Viele Grüße

**Comment by BenediktSeidl** [comment]
ja, das ist möglich, allerdings brauch ich dafür ein paar daten, weil bisher die verschiedenen modelle auch leicht unterschiedliche befehle zum auslesen der daten verwendet haben. ich habe das in einem anderen issue beschrieben was gemacht werden muss:
https://github.com/BenediktSeidl/prpd_usb/issues/1#issuecomment-919226963

alternativ kannst du auch probieren hier dein modell einzutragen:
https://github.com/BenediktSeidl/prpd_usb/blob/78c2fea8654a8afd9d4001bedc2b01b113afeeb1/prpd_usb/schema.py#L104-L106

und dort die verschiedenen befehle ausprobieren:
https://github.com/BenediktSeidl/prpd_usb/blob/78c2fea8654a8afd9d4001bedc2b01b113afeeb1/prpd_usb/schema.py#L9-L11

**Comment by joerglox** [comment]
```
(v) root@raspberrypi:~/prpd_usb# prpd_usb -vvv stdout
2023-12-31 16:56:47,893 WARNING :: root :: starting prpd_usb version 0.1.dev21+g78c2fea
2023-12-31 16:56:47,894 INFO :: prpd_usb.prpd :: opening serial port '/dev/ttyUSB0'
2023-12-31 16:56:47,896 DEBUG :: prpd_usb.prpd :: successfully opened serial port '/dev/ttyUSB0'
2023-12-31 16:56:47,896 DEBUG :: prpd_usb.prpd :: sent request 5a0052500000481ca5, waiting for 25 bytes response
2023-12-31 16:56:49,899 DEBUG :: prpd_usb.prpd :: got response with 0 bytes
Traceback (most recent call last):
  File "/root/prpd_usb/v/bin/prpd_usb", line 8, in <module>
    sys.exit(main())
  File "/root/prpd_usb/v/lib/python3.9/site-packages/prpd_usb/__main__.py", line 85, in main
    with prpd.open(options) as prpd_reader:
  File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
(v) root@raspberrypi:~/prpd_usb#esad {expected_response_length} bytes") line 52,
```

scheint als ob noch irgendwo ein fehler ist oder?
update und upgrade hab ich schon gemacht

Grüße und einen guten Rutsch Jörg

**Comment by BenediktSeidl** [comment]
es schaut so aus als ob er nicht auf den befehl `5a0052500000481ca5` antworten könnte. damit wird das modell und die seriennummer abgefragt:
https://github.com/BenediktSeidl/prpd_usb/blob/78c2fea8654a8afd9d4001bedc2b01b113afeeb1/prpd_usb/schema.py#L98-L101

aber wenn ich das richtig verstanden habe, bist du schon mal weiter gekommen, weil du mir ja schon `9562281` als modell geschickt hast? kann es sein, dass etwas mit der verkabelung nicht stimmt?

**Comment by joerglox** [comment]
hab mir nochmal alles an der Verkabelung angeschaut und finde keinen Fehler. Ich muss derzeit eine USB Verlängerung verwenden, da mein Kabel sonst zu kurz ist. ansonsten läuft auf dem Raspberry noch eine FHEM Installation und an einem weiteren USB Anschluss ist meine Heizung über einen USB Netzwerkwerkadapter angeschlossen. Nachfolgend nochmal der Log und meine schema.py als Anhang, in der ich in den Zeilen 104 - 106 überall den Typ 9562281 eingetragen habe.
Zusätzlich hab ich die schema.py in /site-packages/Prpd_usb/ genau so angepasst wie in /Prpd_usb/
[schema.txt](https://github.com/BenediktSeidl/prpd_usb/files/13804091/schema.txt)

```
login as: root
root@192.168.0.11's password:
Linux raspberrypi 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Last login: Mon Jan  1 10:13:07 2024 from 192.168.0.204
root@raspberrypi:~# cd prpd_usb
root@raspberrypi:~/prpd_usb# python3 -mvenv v
root@raspberrypi:~/prpd_usb# source v/bin/activate
(v) root@raspberrypi:~/prpd_usb# prpd_usb -vvv stdout
2024-01-01 10:19:24,372 WARNING :: root :: starting prpd_usb version 0.1.dev21+g78c2fea
2024-01-01 10:19:24,373 INFO :: prpd_usb.prpd :: opening serial port '/dev/ttyUSB0'
2024-01-01 10:19:24,375 DEBUG :: prpd_usb.prpd :: successfully opened serial port '/dev/ttyUSB0'
2024-01-01 10:19:24,376 DEBUG :: prpd_usb.prpd :: sent request 5a0052500000481ca5, waiting for 25 bytes response
Traceback (most recent call last):
  File "/root/prpd_usb/v/bin/prpd_usb", line 8, in <module>
    sys.exit(main())
  File "/root/prpd_usb/v/lib/python3.9/site-packages/prpd_usb/__main__.py", line 85, in main
    with prpd.open(options) as prpd_reader:
  File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/root/prpd_usb/v/lib/python3.9/site-packages/prpd_usb/prpd.py", line 24, in open
    prpd.init(args.model)
  File "/root/prpd_usb/v/lib/python3.9/site-packages/prpd_usb/prpd.py", line 67, in init
    model, serial_number = self._command(CMD_MODEL)
  File "/root/prpd_usb/v/lib/python3.9/site-packages/prpd_usb/prpd.py", line 47, in _command
    response = self._serial.read(expected_response_length)
  File "/root/prpd_usb/v/lib/python3.9/site-packages/serial/serialposix.py", line 595, in read
    raise SerialException(
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
(v) root@raspberrypi:~/prpd_usb#
```

**Comment by BenediktSeidl** [comment]
hmmmmm. das ist jetzt eine andere fehlermeldung, aber beide haben gemeinsam, dass keine daten vom seriellen port zurück kommen.
das liegt quasi außerhalb vom zuständigkeitsbereich der software die ich geschrieben habe.

das übliche wie neustarten, usb seriell adapter an und abstecken hast du schon ausprobiert?

deine änderung an dem script schaut gut aus, aber leider kommen wir gar nicht bis dahin, weil das script nicht mit dem powerrouter kommunizieren kann.

**Comment by joerglox** [comment]
hab jetzt das System neu aufgesetzt und bekomme leider den gleicher fehler, an was kann das liegen?

**Comment by BenediktSeidl** [comment]
> usb seriell adapter an und abstecken

da habe ich was durcheinander gebracht. du hast ja einfach nur ein usb kabel das direkt in den powerrouter geht, korrekt?
hast du den powerrouter schon mal neu gestartet?
hast du die möglichkeit das ohne usb verlängerung zu testen?

**Comment by joerglox** [comment]
Hi alles ausprobiert, war zwar ein akt aber nein es funktioniert einfach nicht
